<?xml version="1.0" encoding="windows-1252" ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><link rel="stylesheet" type="text/css" href="../../../../_rhdefault.css"/>
<meta http-equiv="Content-Type" content="text/html; charset=WINDOWS-1252"/>
<meta name="topic-status" content="Complete"/>
<meta name="generator" content="Adobe RoboHelp 2022"/>
<title>Fifth Exercise Adding the Third Part</title>
<link rel="StyleSheet" href="../../../../assets/css/default.css" type="text/css"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/><script type="text/javascript" src="../../../../ehlpdhtm.js"></script></head>
<body>
<h1>Fifth Exercise Adding the Third Part</h1>
<ol style="list-style: decimal;">
<li class="p">
<p class="Indent_1_Bulllet">Click on a Face <img src="../../../../assets/images/image181.gif" alt="" style="border: none;" width="45" height="21" border="0"/> ortho view.</p>
</li>
<li class="p">
<p class="Indent_1_Bulllet">Click on &quot;New Part&quot;.  We will be adding the center-piece.  In the &quot;Part Type&quot; area select &quot;Board&quot; as the part type then click &quot;Next&quot;.</p>
</li>
<li class="p">
<p class="Indent_1_Bulllet">In the &quot;Size&quot; window set the size to be 10.75&quot;L by 10.75&quot;W.  This is the center-piece of our corbel and it will be running up and down with its &quot;Face&quot; facing left.  Its length will be the height of the cabinet minus the thickness of board@1 minus .5&quot; just to make it look better (12 - .75 = 11.25) (11.25 - .5 = 10.75).  Its width will be the depth of the cabinet minus the thickness of board@2 minus .5&quot; just to make it look better (12 - .75 = 11.25) (11.25 - .5 = 10.75).  Click on &quot;Next&quot;.</p>
</li>
<li class="p">
<p class="Indent_1_Bulllet">In the &quot;Orientation&quot; window leave the orientation set to &quot;Front&quot;.  Click on &quot;Next&quot;.</p>
</li>
<li class="p">
<p class="Indent_1_Bulllet">In the &quot;Finish&quot; window set the finish to &quot;Exterior&quot; for the front, back, and edges.   Click on the &quot;Finish&quot; button.</p>
</li>
</ol>
<p>You will now be at a Face <img src="../../../../assets/images/image181.gif" alt="" style="border: none;" width="45" height="21" border="0"/> ortho view and on the left side of your screen the &quot;Left/Right&quot; will be &quot;-1.25&quot;.  Before we position the part we will rotate it.  Looking at the corbel from different ortho views <img src="../../../../assets/images/image181.gif" alt="" style="border: none;" width="45" height="21" border="0"/><img src="../../../../assets/images/image182.gif" alt="" style="border: none;" width="44" height="21" border="0"/><img src="../../../../assets/images/image183.gif" alt="" style="border: none;" width="42" height="21" border="0"/> and also looking at it from the 3D view we can see that this part needs to turn so that the &quot;Face&quot; of the part is facing left.  In order to turn the part to face left it is the Y-axis that will be acting like a hinge.  In order to face the reference point we will have to look at this last piece from a &quot;Plan&quot; <img src="../../../../assets/images/image182.gif" alt="" style="border: none;" width="44" height="21" border="0"/> ortho view.</p>
<ol start="6" style="list-style: decimal;">
<li class="p">
<p class="Indent_1_Bulllet">Click on the &quot;Plan&quot; <img src="../../../../assets/images/image182.gif" alt="" style="border: none;" width="44" height="21" border="0"/> ortho view tab.</p>
</li>
<li class="p">
<p class="Indent_1_Bulllet">Click on the part.  In the &quot;Rotation&quot; area we will need to enter a &quot;–90&quot; for the part to rotate clockwise.  Enter –90 and press enter.</p>
</li>
</ol>
<p>Look at where the reference point for this part is located.  This part needs to be centered in the cabinet left and right, <span style="font-weight: bold;">one half of the width of the cabinet</span> (the cabinet should be 2.5&quot;) is 1.25&quot; but the reference point for the BOARD is on the right side, so we can&#39;t just say the &quot;Left/Right&quot; is 1.25&quot;, because the BOARD would be off center.  So we must <span style="font-weight: bold;">add one half the thickness of the part</span> to the 1.25&quot;. 1.25 + .375 = 1.625.</p>
<ol start="8" style="list-style: decimal;">
<li class="p">
<p class="Indent_1_Bulllet">So we enter 1.625 into the &quot;Left/Right&quot; and press enter.</p>
</li>
</ol>
<p>Look at this part; notice where the reference point is located as you can see the board needs to moved forward by the thickness of board@2.</p>
<ol start="9" style="list-style: decimal;">
<li class="p">
<p class="Indent_1_Bulllet">Type .75 into the &quot;In/Out&quot; area and press enter.</p>
</li>
<li class="p">
<p class="Indent_1_Bulllet">The part needs to move up .5&quot; type .5 in the &quot;Up/Down&quot; area and press enter.</p>
</li>
</ol>
<p>All three parts are now rotated and positioned correctly, and we are ready to give them intelligence.  So that if we change the width, height, or depth of the cabinet the parts will grow, and shrink, and move accordingly.</p>


</body></html>